### ISSUE TITLE
"What's the purpose?" / "Why should we use this?"

### ISSUE THREAD

**Issue by F1nx** [vercel/hyper-site#152]
### **I know these are simple questions, but I have been genuinely curious about using this terminal over others that are out there, and I have not been able to find a clear reason why I or we should even use it.** 
Upon further inspection, I do see that you state `These shell commands are defined internally.`, meaning that it is completely based on the actual command lines running on every operating system. What difference would it make if I had Hyper, then?

 _Maybe it is on my side_, a common person, in addition to being a mere novice to coding and JavaScript. Please, let me know if I have any misconceptions! Though, it would be helpful, anyhow, if you could have your documentation make the purpose (more) apparent.

**Comment by adebiyial** [comment]
Hyper is a new kind of terminal, built on top of web technology, with a focus on extensibility. This opens new possibilities that can make the CLI experience [more productive](https://github.com/chabou/hyper-pane) (and [fun](https://github.com/Aaronius/hyper-cat))!

Read more on the [hyper blog](https://hyper.is/blog)
