### ISSUE TITLE
Links don't stand out

### ISSUE THREAD

**Issue by ptrkcsk** [vercel/hyper-site#195]
Links have almost the same styling as surrounding body text

<img width="1904" alt="Screen Shot 2020-06-10 at 7 52 20 PM" src="https://user-images.githubusercontent.com/4766244/84329952-0fdd8600-ab54-11ea-945c-24d60de041e6.png">

**Comment by vassbence** [comment]
I'm currently working on the landing page animation and then will clean up the remaining CSS on the page, will definitely include a fix for this too.

Thanks!

**Comment by vassbence** [comment]
Fixed in #193
