### ISSUE TITLE
switch to code elements from carbon for the syntax highlighting

### ISSUE THREAD

**Issue by oguzzkilic** [vercel/hyper-site#98]
example from localhost. 
--

what do you think about this matter?

![screen shot 2019-02-04 at 07 51 54](https://user-images.githubusercontent.com/3652404/52190715-c4c1ad80-2851-11e9-90ca-8d15e9f7b80f.png)

**Comment by MAPESO** [comment]
@oguzzkilic I think it's a good idea but I could break with the design  

@evilrabbit what's your opinion about it ?

**Comment by pacocoursey** [comment]
I'm not a fan of showing a full console image, but it would be great to have a better syntax highlighting theme for our code snippets instead of all green.

Feel free to PR that if you're interested @oguzzkilic @markozxuu 👍
